name: my home
title: my home
#resources: !include_dir_list lovelace/resources
resources:
  - url: /local/community/weather-card/weather-card.js
    type: module
custom_header: !include lovelace/cards/custom_header.yaml
views:
  - !include lovelace/views/mobile.yaml
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/notify.yaml
  - !include lovelace/views/weather.yaml